name: Deploy to Mikrus

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: |
          npm run build
      - name: Remove old files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MIKRUS_SSH_SERVER }}
          username: ${{ secrets.MIKRUS_SSH_USER }}
          key: ${{ secrets.MIKRUS_SSH_KEY }}
          port: ${{ secrets.MIKRUS_SSH_PORT }}
          script: |
            rm -rf /root/agatastan/*
      - name: Deploy scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.MIKRUS_SSH_SERVER }}
          username: ${{ secrets.MIKRUS_SSH_USER }}
          key: ${{ secrets.MIKRUS_SSH_KEY }}
          port: ${{ secrets.MIKRUS_SSH_PORT }}
          source: "out/*"
          target: "/root/agatastan/"
      - name: Restart nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MIKRUS_SSH_SERVER }}
          username: ${{ secrets.MIKRUS_SSH_USER }}
          key: ${{ secrets.MIKRUS_SSH_KEY }}
          port: ${{ secrets.MIKRUS_SSH_PORT }}
          script: |
            docker restart nginx
